---

Device_info :

    Device_type : GPU
    GPU_COUNT : 1
    ctx : 0

Training_parameter:
    
    optimizer : RMSprop
    lr_scheduler : exponential_decay
    loss : L2
    learning_rate : 0.005
    epochs : 200
    batch_size : 32
    
   
