---

Device_info :

    Device_type : GPU
    GPU_COUNT : 1
    ctx : 3

Training_parameter:
    
    optimizer : Adam
    lr_scheduler : exponential_decay
    loss : L2
    learning_rate : 0.01
    epochs : 200
    batch_size : 32
    
   
